snd-soc-ac108-objs := ac108.o
snd-soc-ac107-objs := ac107.o
snd-soc-dmic-objs := dmic.o

obj-$(CONFIG_SND_SOC_AC108)	+= snd-soc-ac108.o
obj-$(CONFIG_SND_SOC_AC107)	+= snd-soc-ac107.o
obj-$(CONFIG_SND_SOC_DMIC)	+= snd-soc-dmic.o
